In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
unlinked = pd.read_excel("Cleaned Data/Unlinked_Merged.xlsx")
linked = pd.read_excel("Cleaned Data/cleaned_linkedmeta_updated.xlsx")

In [3]:
cols_to_drop = [
    "inj vol", "2FL", "DFLAC", "3SL", "6SL", "LNT", "LNnT",
    "LNFPI", "LNFPII", "LNFPIII", "LSTc", "DFLNT", "DSLNT",
    "DFLNH", "FDSLNH", "DSLNH", 'Secretor Status', 'secretorstatus_mom'
]

unlinked = unlinked.drop(columns=cols_to_drop, errors="ignore")

In [4]:
linked = linked.rename(columns={"Linked?": "Linked"})

In [5]:
print(unlinked.columns)
linked.columns

Index(['Subject ID', 'sample_unique_id', 'CGA', 'DOL', 'Current Weight',
       'Current Height', 'Current HC', 'Scavenged/Fresh?', 'Type of Milk',
       'HMF', 'TPN', 'Iron', 'Linked', 'Infant Sex', 'Birth Weight (g)',
       'Birth Length (cm)', 'Birth HC (cm)', 'LOS (days)', 'Aliquots_num',
       'scavenged notes', 'Sample Source'],
      dtype='object')

Index(['Subject ID', 'sample_unique_id', 'CGA', 'DOL', 'Current Weight',
       'Current Height', 'Current HC', 'Scavenged/Fresh?', 'Type of Milk',
       'HMF', 'TPN', 'Iron', 'Iron Date & time', 'Feeding Duration', 'Linked',
       'feeding time', 'Collection date/aliquot time for all samples',
       'Milk Prep Room Expiration Date & Time', 'Sample Source',
       'Aliquots_num'],
      dtype='object')

In [6]:
merged_df = pd.concat([unlinked, linked], ignore_index=True, sort=False)

In [7]:
merged_df

,Subject ID,sample_unique_id,CGA,DOL,Current Weight,Current Height,Current HC,Scavenged/Fresh?,Type of Milk,HMF,...,Birth HC (cm),LOS (days),Aliquots_num,scavenged notes,Sample Source,Iron Date & time,Feeding Duration,feeding time,Collection date/aliquot time for all samples,Milk Prep Room Expiration Date & Time
0,NB00012,NB00012_M_1,28.4,27.0,1430.0,32.0,26.0,Scavenged,MOM + DBM,Y,...,23.8,31.0,5,NaN,Prepped in Milk Room,NaN,NaN,NaN,NaN,NaN
1,NB00003,NB00003_M_1,29.0,22.0,995.0,35.7,23.7,Scavenged,DBM,Y,...,24.0,130.0,2,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN
2,NB00003,NB00003_M_2,29.0,22.0,1005.0,36.0,24.4,Scavenged,DBM,Y,...,24.0,130.0,1,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN
3,NB00003,NB00003_M_3,29.3,25.0,1065.0,36.0,24.3,Scavenged,DBM,Y,...,24.0,130.0,1,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN
4,NB00354,NB00354_M_1,29.4,12.0,1005.0,34.0,34.5,Scavenged,MOM,Y,...,34.5,97.0,7,NaN,Prepped in Milk Room,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,NB00469,NB00469_M_2,34.1,25.0,2040.0,42.5,30.3,Scavenged,MOM,Y+Nutramigen,...,NaN,NaN,2,NaN,Scavenged,2025-05-09 21:09:00,unknown,2025-05-09 08:30:00,2025-05-09 12:12:00,2025-05-09 16:06:00
265,NB00486,NB00486_M_1,32.1,9.0,1055.0,36.0,26.7,Scavenged,DBM,Y,...,NaN,NaN,8,NaN,Prepped in Milk Room,NaN,NaN,Prepped 5/13/25 PM,2025-05-14 10:45:00,NaN
266,NB00486,NB00486_M_2,32.1,9.0,1055.0,36.0,26.7,Scavenged,DBM,Y,...,NaN,NaN,1,NaN,Scavenged,NaN,unknown,5/14/2025 done @ 08:11,2025-05-14 10:45:00,2025-05-14 17:37:00
267,NB00487,NB00487_M_1,34.2,7.0,1940.0,44.3,29.0,Scavenged,MOM+DBM,Y,...,NaN,NaN,7,NaN,Prepped in Milk Room,NaN,NaN,Prepped 5/13/25 PM,2025-05-14 11:00:00,NaN
268,NB00487,NB00487_M_2,34.2,7.0,1940.0,44.3,29.0,Scavenged,MOM+DBM,Y,...,NaN,NaN,1,NaN,Scavenged,NaN,90,2025-05-14 08:58:00,2025-05-14 11:00:00,2025-05-14 17:47:00

#### remove twin samples

In [8]:
merged_df['is_twin'] = merged_df['sample_unique_id'].str.contains('/')
merged_df[['sample_unique_id', 'is_twin']]
print(merged_df[merged_df['is_twin']][['sample_unique_id', 'is_twin']])
merged_df_no_twins = merged_df[~merged_df['is_twin']].copy()
merged_df = merged_df_no_twins
merged_df

              sample_unique_id  is_twin
234  NB00405_M_5 / NB00406_M_7     True
260    NB00467_M_1/NB00438_M_4     True

,Subject ID,sample_unique_id,CGA,DOL,Current Weight,Current Height,Current HC,Scavenged/Fresh?,Type of Milk,HMF,...,LOS (days),Aliquots_num,scavenged notes,Sample Source,Iron Date & time,Feeding Duration,feeding time,Collection date/aliquot time for all samples,Milk Prep Room Expiration Date & Time,is_twin
0,NB00012,NB00012_M_1,28.4,27.0,1430.0,32.0,26.0,Scavenged,MOM + DBM,Y,...,31.0,5,NaN,Prepped in Milk Room,NaN,NaN,NaN,NaN,NaN,False
1,NB00003,NB00003_M_1,29.0,22.0,995.0,35.7,23.7,Scavenged,DBM,Y,...,130.0,2,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN,False
2,NB00003,NB00003_M_2,29.0,22.0,1005.0,36.0,24.4,Scavenged,DBM,Y,...,130.0,1,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN,False
3,NB00003,NB00003_M_3,29.3,25.0,1065.0,36.0,24.3,Scavenged,DBM,Y,...,130.0,1,NaN,Scavenged,NaN,NaN,NaN,NaN,NaN,False
4,NB00354,NB00354_M_1,29.4,12.0,1005.0,34.0,34.5,Scavenged,MOM,Y,...,97.0,7,NaN,Prepped in Milk Room,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,NB00469,NB00469_M_2,34.1,25.0,2040.0,42.5,30.3,Scavenged,MOM,Y+Nutramigen,...,NaN,2,NaN,Scavenged,2025-05-09 21:09:00,unknown,2025-05-09 08:30:00,2025-05-09 12:12:00,2025-05-09 16:06:00,False
265,NB00486,NB00486_M_1,32.1,9.0,1055.0,36.0,26.7,Scavenged,DBM,Y,...,NaN,8,NaN,Prepped in Milk Room,NaN,NaN,Prepped 5/13/25 PM,2025-05-14 10:45:00,NaN,False
266,NB00486,NB00486_M_2,32.1,9.0,1055.0,36.0,26.7,Scavenged,DBM,Y,...,NaN,1,NaN,Scavenged,NaN,unknown,5/14/2025 done @ 08:11,2025-05-14 10:45:00,2025-05-14 17:37:00,False
267,NB00487,NB00487_M_1,34.2,7.0,1940.0,44.3,29.0,Scavenged,MOM+DBM,Y,...,NaN,7,NaN,Prepped in Milk Room,NaN,NaN,Prepped 5/13/25 PM,2025-05-14 11:00:00,NaN,False
268,NB00487,NB00487_M_2,34.2,7.0,1940.0,44.3,29.0,Scavenged,MOM+DBM,Y,...,NaN,1,NaN,Scavenged,NaN,90,2025-05-14 08:58:00,2025-05-14 11:00:00,2025-05-14 17:47:00,False

## Add in Z-scores

### PMA calculation

In [9]:
# GA_birth_weeks = CGA_weeks - DOL/7

merged_df['GA_birth_weeks'] = merged_df['CGA'] - (merged_df['DOL'] / 7)

merged_df[['sample_unique_id','CGA', 'DOL','GA_birth_weeks']]

    sample_unique_id   CGA   DOL  GA_birth_weeks
0        NB00012_M_1  28.4  27.0       24.542857
1        NB00003_M_1  29.0  22.0       25.857143
2        NB00003_M_2  29.0  22.0       25.857143
3        NB00003_M_3  29.3  25.0       25.728571
4        NB00354_M_1  29.4  12.0       27.685714
..               ...   ...   ...             ...
264      NB00469_M_2  34.1  25.0       30.528571
265      NB00486_M_1  32.1   9.0       30.814286
266      NB00486_M_2  32.1   9.0       30.814286
267      NB00487_M_1  34.2   7.0       33.200000
268      NB00487_M_2  34.2   7.0       33.200000

[267 rows x 4 columns]

In [10]:
# 2) Get a stable GA_birth per infant from the best available rows
ga_birth_by_infant = (
    merged_df
    .loc[merged_df['GA_birth_weeks'].notna(), ['sample_unique_id', 'GA_birth_weeks']]
    .groupby('sample_unique_id')['GA_birth_weeks']
    .median()   # median is robust if you have multiple rows with slight rounding noise
)

In [11]:
pma_from_cga = merged_df['CGA']
pma_from_ga_birth = merged_df['GA_birth_weeks'] + (merged_df['DOL'] / 7.0)

In [12]:
merged_df['PMA_weeks'] = np.where(pma_from_cga.notna(), pma_from_cga, pma_from_ga_birth)

In [14]:
# 5) QC flags
merged_df['qc_ga_birth_implausible'] = (
    (merged_df['GA_birth_weeks'] < 22) | (merged_df['GA_birth_weeks'] > 42)
)

merged_df['qc_pma_missing'] = merged_df['PMA_weeks'].isna()

In [21]:
merged_df[['sample_unique_id','CGA', 'DOL','GA_birth_weeks', 'PMA_weeks']]

    sample_unique_id   CGA   DOL  GA_birth_weeks  PMA_weeks
0        NB00012_M_1  28.4  27.0       24.542857       28.4
1        NB00003_M_1  29.0  22.0       25.857143       29.0
2        NB00003_M_2  29.0  22.0       25.857143       29.0
3        NB00003_M_3  29.3  25.0       25.728571       29.3
4        NB00354_M_1  29.4  12.0       27.685714       29.4
..               ...   ...   ...             ...        ...
264      NB00469_M_2  34.1  25.0       30.528571       34.1
265      NB00486_M_1  32.1   9.0       30.814286       32.1
266      NB00486_M_2  32.1   9.0       30.814286       32.1
267      NB00487_M_1  34.2   7.0       33.200000       34.2
268      NB00487_M_2  34.2   7.0       33.200000       34.2

[267 rows x 5 columns]

### Z-score formula

In [25]:
merged_df.columns

Index(['Subject ID', 'sample_unique_id', 'CGA', 'DOL', 'Current Weight',
       'Current Height', 'Current HC', 'Scavenged/Fresh?', 'Type of Milk',
       'HMF', 'TPN', 'Iron', 'Linked', 'Infant Sex', 'Birth Weight (g)',
       'Birth Length (cm)', 'Birth HC (cm)', 'LOS (days)', 'Aliquots_num',
       'scavenged notes', 'Sample Source', 'Iron Date & time',
       'Feeding Duration', 'feeding time',
       'Collection date/aliquot time for all samples',
       'Milk Prep Room Expiration Date & Time', 'is_twin', 'GA_birth_weeks',
       'PMA_weeks', 'qc_ga_birth_implausible', 'qc_pma_missing'],
      dtype='object')

In [26]:
# >>> EDIT THESE TO MATCH YOUR DATA <<<
AGE_COL   = "PMA_weeks"                # your PMA
SEX_COL   = "Infant Sex"                      # your sex column
WEIGHT_COL= "Current Weight"                 # grams
LENGTH_COL= "Current Height"                # cm (aka length/height)
HC_COL    = "Current HC"                     # cm

# map your sex values to reference sex labels used in ref_df ("male"/"female")
SEX_MAP = {
    "M": "male", "F": "female",
    "Male": "male", "Female": "female",
    "m": "male", "f": "female",
    1: "male", 2: "female",
}

In [27]:
# ---- LMS z-score helper ----
def lms_z(x, L, M, S):
    x = np.asarray(x, dtype=float)
    L = np.asarray(L, dtype=float)
    M = np.asarray(M, dtype=float)
    S = np.asarray(S, dtype=float)
    out = np.empty_like(x, dtype=float)
    mask = np.isclose(L, 0.0)
    out[mask]  = np.log(x[mask] / M[mask]) / S[mask]
    out[~mask] = ((x[~mask] / M[~mask])**L[~mask] - 1) / (L[~mask] * S[~mask])
    return out

In [28]:
# ---- Interpolate L, M, S at arbitrary ages for each (sex, measure) ----
def interpolate_lms_for_rows(age, sex, measure, ref_df):
    L_arr = np.empty(len(age), dtype=float)
    M_arr = np.empty(len(age), dtype=float)
    S_arr = np.empty(len(age), dtype=float)

    keys = pd.Series(list(zip(sex, measure)))
    for (sx, ms), idx in keys.groupby(keys).groups.items():
        sub = ref_df[(ref_df["sex"] == sx) & (ref_df["measure"] == ms)].sort_values("pma_weeks")
        if sub.empty:
            raise ValueError(f"No reference rows for sex={sx} & measure={ms}. Check SEX_MAP/measure names.")

        x = age[idx].astype(float)
        x = np.clip(x, sub["pma_weeks"].min(), sub["pma_weeks"].max())

        L_arr[idx] = np.interp(x, sub["pma_weeks"], sub["L"])
        M_arr[idx] = np.interp(x, sub["pma_weeks"], sub["M"])
        S_arr[idx] = np.interp(x, sub["pma_weeks"], sub["S"])
    return L_arr, M_arr, S_arr

In [29]:
# ---- Main: add z-scores to your metadata df ----
def add_intergrowth_zscores(df, ref_df):
    out = df.copy()

    # normalize sex labels
    out["_sex_ref"] = out[SEX_COL].map(SEX_MAP)
    if out["_sex_ref"].isna().any():
        bad = out.loc[out["_sex_ref"].isna(), SEX_COL].unique()
        raise ValueError(f"Unmapped sex values in '{SEX_COL}': {bad}. Update SEX_MAP.")

    age = out[AGE_COL].astype(float).to_numpy()

    # weight: grams -> kg (INTERGROWTH weight M is in kg)
    w_kg = (out[WEIGHT_COL].astype(float) / 1000.0).to_numpy()
    Lw, Mw, Sw = interpolate_lms_for_rows(
        age=age,
        sex=out["_sex_ref"].to_numpy(),
        measure=np.array(["weight"] * len(out)),
        ref_df=ref_df
    )
    out["z_weight_for_age"] = lms_z(w_kg, Lw, Mw, Sw)

    # length: cm
    len_cm = out[LENGTH_COL].astype(float).to_numpy()
    Ll, Ml, Sl = interpolate_lms_for_rows(
        age=age,
        sex=out["_sex_ref"].to_numpy(),
        measure=np.array(["length"] * len(out)),
        ref_df=ref_df
    )
    out["z_length_for_age"] = lms_z(len_cm, Ll, Ml, Sl)

    # head circumference: cm
    hc_cm = out[HC_COL].astype(float).to_numpy()
    Lh, Mh, Sh = interpolate_lms_for_rows(
        age=age,
        sex=out["_sex_ref"].to_numpy(),
        measure=np.array(["hc"] * len(out)),
        ref_df=ref_df
    )
    out["z_hc_for_age"] = lms_z(hc_cm, Lh, Mh, Sh)

    # optional QC
    out["qc_extreme_z"] = (
        (out["z_weight_for_age"].abs() > 3) |
        (out["z_length_for_age"].abs() > 3) |
        (out["z_hc_for_age"].abs() > 3)
    )

    return out.drop(columns=["_sex_ref"])

In [ ]:
# Assuming you already have:
# df = your NICU metadata (from CSV or dataframe in memory)
# ref_df = your INTERGROWTH LMS reference table

df_z = add_intergrowth_zscores(merged_df, ref_df)

In [ ]:
def calc_zscore(value, sex, pma_weeks, measure, ref_df):
    ref = ref_df[(ref_df['sex'] == sex) &
                 (ref_df['pma_weeks'] == round(pma_weeks)) &
                 (ref_df['measure'] == measure)]
    L, M, S = ref[['L','M','S']].values[0]
    if L == 0:
        return np.log(value/M)/S
    else:
        return ((value/M)**L - 1) / (L*S)

## Milk Information

In [ ]:
merged_df["Type of Milk"].value_counts()

In [ ]:
merged_df['Type of Milk'] = merged_df['Type of Milk'].replace('MOM + DBM', 'MOM+DBM')

In [ ]:
merged_df['Type of Milk'] = merged_df['Type of Milk'].replace('Switched to Fortifier ', 'Switched to Formula')

In [ ]:
merged_df = merged_df[~merged_df['Type of Milk'].isin(['FBM/MBM'])]

In [ ]:
merged_df["Type of Milk"].value_counts()

In [ ]:
merged_df["Sample Source"].value_counts()

In [ ]:
merged_df["Infant Sex"] = merged_df["Infant Sex"].str.strip()

In [ ]:
merged_df["Infant Sex"].value_counts()

In [ ]:
merged_df["Linked"].value_counts()

In [ ]:
merged_df.to_excel("Cleaned Data/merged_df.xlsx", index=False)
merged_df

## Merge in Area Counts

#### Clean up AC Report

In [ ]:
AC = pd.read_excel("Raw Data/NeoBANK AC REPORT.xlsx")
AC

In [ ]:
AC.drop(columns=["Sample#", "ID_internal"], inplace=True)

In [ ]:
AC

In [ ]:
new_columns = [
    "sample_unique_id", "secretor_status", "Diversity", "Evenness", "2FL", "3FL", "DFLac", "3'SL", "6SL",
    "LNT", "LNnT", "LNFP I", "LNFP II", "LNFP III", "LSTb", "LSTc", "DFLNT", "LNH",
    "DSLNT", "FLNH", "DFLNH", "FDSLNH", "DSLNH", "SUM", "Sia", "Fuc",
    "2FL", "3FL", "DFLac", "3SL", "6SL", "LNT", "LNnT", "LNFP I", "LNFP II",
    "LNFP III", "LSTb", "LSTc", "DFLNT", "LNH", "DSLNT", "FLNH", "DFLNH", "FDSLNH",
    "DSLNH", "SUM",
    "2FL", "3FL", "DFLac", "3SL", "6SL", "LNT", "LNnT", "LNFP I", "LNFP II",
    "LNFP III", "LSTb", "LSTc", "DFLNT", "LNH", "DSLNT", "FLNH", "DFLNH", "FDSLNH",
    "DSLNH", "SUM"
]

AC.columns = new_columns
AC

In [ ]:
# Get the first two "special" columns
id_cols = ["sample_unique_id", "secretor_status"]

# Define your HMO base names
hmo_names = [
    "2FL","3FL","DFLac","3SL","6SL","LNT","LNnT","LNFP I","LNFP II","LNFP III",
    "LSTb","LSTc","DFLNT","LNH","DSLNT","FLNH","DFLNH","FDSLNH","DSLNH","SUM","Sia","Fuc"
]

# Build expanded lists for units
columns_nmol = [f"{hmo} [nmol/mL]" for hmo in hmo_names]
columns_ug   = [f"{hmo} [µg/mL]"   for hmo in hmo_names]
columns_pct  = [f"{hmo} [%]"       for hmo in hmo_names]

# Combine into new header
new_columns = id_cols + ["Diversity", "Evenness"] + columns_nmol + columns_ug + columns_pct

# Assign back (ensuring the length matches the dataframe)
AC.columns = new_columns[:AC.shape[1]]
AC

In [ ]:
AC = AC.drop(index=0)
AC

### Merge on metadata

In [ ]:
merged_all = merged_df.merge(
    AC,
    on="sample_unique_id",
    how="left"   # keeps all rows from merged_df, adds HMO data where available
)
merged_all

In [ ]:
cols = [
    "is twin"
]

mereged_all = merged_all.drop(columns=cols, errors="ignore")

In [ ]:
# Make sure column names are clean
merged_all.columns = merged_all.columns.str.strip()

# Treat blanks/strings like "nan"/"None" as missing in Subject ID
sid = (merged_all["Subject ID"]
       .astype("string")
       .str.strip()
       .replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "None": pd.NA}))

# Extract NB code from sample_unique_id (everything before the first underscore)
sid_from_suid = (merged_all["sample_unique_id"]
                 .astype("string")
                 .str.extract(r"^([^_]+)")[0])

# Fill only where Subject ID is missing/blank
merged_all["Subject ID"] = sid.fillna(sid_from_suid)

# (Optional) standardize case
# df["Subject ID"] = df["Subject ID"].str.upper()

# Quick sanity check
print("Remaining missing Subject ID rows:", merged_all["Subject ID"].isna().sum())
merged_all.loc[merged_all["Subject ID"].isna(), ["sample_unique_id"]].head()

In [ ]:
# Extract the prefix from sample_unique_id
prefix_from_suid = merged_all["sample_unique_id"].astype("string").str.extract(r"^([^_]+)")[0]

# Boolean mask: True where mismatch occurs
mismatch_mask = merged_all["Subject ID"].astype("string").str.strip() != prefix_from_suid

# Get the rows where Subject ID and sample_unique_id prefix don't match
mismatches = merged_all.loc[mismatch_mask, ["Subject ID", "sample_unique_id"]]

print(f"Number of mismatches: {mismatches.shape[0]}")
mismatches.head(20)  # show first 20 mismatches

In [ ]:
merged_all["moms_secretor_status"] = merged_all.apply(
    lambda row: row["secretor_status"] if row["Type of Milk"] == "MOM" else pd.NA,
    axis=1
)

# Quick check
merged_all[["Subject ID", "Type of Milk", "secretor_status", "moms_secretor_status"]].head(20)

#### save to cleaned file

In [ ]:
merged_all.to_excel("Cleaned Data/merged_ALL.xlsx", index=False)
merged_all

In [ ]:
# Check if linked subjects have HMO data
linked_with_y = merged_all[merged_all["Linked"] == "Y"]


hmo_columns = [col for col in merged_all.columns if col.endswith("[nmol/mL]")]


print("Number of linked rows:", linked_with_y.shape[0])
print("Number of linked rows with HMO values:", linked_with_y[hmo_columns].notna().sum().sum())
linked_with_y[hmo_columns].head()